# Generated by Django 5.2.2 on 2025-06-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacontable',
            name='tipo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('Capital', 'Capital Contable'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=10),
        ),
    ]
