# Generated by Django 5.2.2 on 2025-06-09 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0002_alter_cuentacontable_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisHorizontal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacion_absoluta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variacion_relativa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_estado', models.CharField(choices=[('BALANCE', 'Balance General'), ('RESULTADOS', 'Estado de Resultados')], max_length=20)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_contable.cuentacontable')),
                ('periodo_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_base', to='sistema_contable.periodocontable')),
                ('periodo_comparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_comparacion', to='sistema_contable.periodocontable')),
            ],
            options={
                'unique_together': {('cuenta', 'periodo_base', 'periodo_comparacion', 'tipo_estado')},
            },
        ),
        migrations.CreateModel(
            name='AnalisisVertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_estado', models.CharField(choices=[('BALANCE', 'Balance General'), ('RESULTADOS', 'Estado de Resultados')], max_length=20)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_contable.cuentacontable')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_contable.periodocontable')),
            ],
            options={
                'unique_together': {('periodo', 'cuenta', 'tipo_estado')},
            },
        ),
    ]
