# Generated by Django 5.2.2 on 2025-06-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0003_analisishorizontal_analisisvertical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacontable',
            name='tipo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio Neto'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=10),
        ),
    ]
