# Generated by Django 5.2.2 on 2025-06-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_contable', '0005_rename_ruc_empresa_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
